substitutions:
  wakeup_with_button_press_dimmed: true

packages:
  radiowaves: !include nspanel_esphome_addon_espectre+bluetooth.yaml 

  climate: !include nspanel_esphome_addon_climate_backup.yaml # ready to test